name: chatgpt-github-review-pull-request
description: GitHub action that adds ChatGPT code review comments to pull requests
inputs:
  model:
    description: 'OpenAI model'
    default: 'gpt-4-turbo'
    required: false
  max_tokens:
    description: 'max TPM for OpenAI'
    default: 4096
    required: false
runs:
  using: node16
  main: dist/index.js
branding:
  icon: 'message-circle'
  color: 'yellow'